version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: market-sentinel
      POSTGRES_PASSWORD: market-sentinel-password
    volumes:
      - ./data_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432